web_app_weather/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import CitiesViewSet


app_name = 'api'

router = DefaultRouter()
router.register(r'weather', CitiesViewSet, basename='weather')

urlpatterns = [
    path('', include(router.urls)),
]

web_app_weather/metcast/urls.py
from django.urls import path

from . import views
from .views import CityAutocomplete

app_name = 'metcast'

urlpatterns = [
    path('', views.WeatherCreateView.as_view(),
         name='create'),
    path('detail/<str:city>/',
         views.WeatherDetailView.as_view(),
         name='detail'),
    path('city-autocomplete/',
         CityAutocomplete.as_view(),
         name='city-autocomplete'),
]

web_app_weather/web_app_weather/urls.py
"""Главный файл с URL."""
from django.contrib import admin
from django.urls import path
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('metcast.urls', namespace='metcast')),
    path('api/', include('api.urls', namespace='api')),
]

web_app_weather/metcast/models.py
from django.db import models
from django.urls import reverse


class Weather(models.Model):
    city = models.CharField(max_length=100,
                            unique=True,
                            blank=False,
                            null=False
                            )
    count_call = models.IntegerField(default=1)

    def get_absolute_url(self):
        return reverse('metcast:detail', kwargs={'city': self.city})

    def __str__(self):
        return self.city

web_app_weather/metcast/forms.py
from django import forms

from .models import Weather


class WeatherForm(forms.ModelForm):
    """Форма для ввода города."""

    class Meta:
        model = Weather
        fields = ('city', )

web_app_weather/api/views.py
from rest_framework import viewsets

from metcast.models import Weather
from .serializers import WeatherSerializer


class CitiesViewSet(viewsets.ModelViewSet):
    """Представление для API к модели погода.
    Укажите в параметрах запроса конкретный город для
    получения информации по определенному городу.
    """

    queryset = Weather.objects.all()
    serializer_class = WeatherSerializer

    def get_queryset(self):
        city = self.request.query_params.get('city', None)
        if city:
            return self.queryset.filter(city=city)
        return self.queryset

web_app_weather/metcast/views.py
from django.views.generic import CreateView, DetailView
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.http import JsonResponse
from django.views import View

from .models import Weather
from .forms import WeatherForm
from .utils import get_weather_forecast


class WeatherCreateView(CreateView):
    """Представление страницы ввода города."""

    model = Weather
    form_class = WeatherForm
    template_name = 'metcast/weather_form.html'

    def post(self, request, *args, **kwargs):
        city = request.POST.get('city')
        if Weather.objects.filter(city=city).exists():
            weather = Weather.objects.get(city=city)
            weather.count_call += 1
            weather.save()
            return redirect('metcast:detail', city=weather.city)
        weather = Weather.objects.create(city=city)
        return redirect('metcast:detail', city=weather.city)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.count_call = 1
        self.object.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('metcast:detail', kwargs={'city': self.object.city})


class WeatherDetailView(DetailView):
    """Представление отдельного города и информации о погоде в нем."""

    model = Weather
    template_name = 'metcast/weather_detail.html'
    slug_field = 'city'
    slug_url_kwarg = 'city'

    def get_object(self):
        return get_object_or_404(Weather, city=self.kwargs['city'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['weather_cost'] = get_weather_forecast(
            self.object.city
        )
        return context


class CityAutocomplete(View):
    """Класс для автозаполнения поля "Города"."""

    def get(self, request, *args, **kwargs):
        if 'term' in request.GET:
            qs = Weather.objects.filter(
                city__icontains=request.GET.get('term')
            )
            cities = list(qs.values_list('city', flat=True))
            return JsonResponse(cities, safe=False)
        return JsonResponse([], safe=False)

web_app_weather/templates/metcast/weather_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ object.city }}</title>
</head>
<body>
   Город: {{ object.city }}</br>
   Погода: {{ weather_cost }}</br>
</body>
</html>

web_app_weather/templates/metcast/weather_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Прогноз погоды</title>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
</head>
  <h1>Создать запись</h1>

  <div class="card col-4">
    <div class="card-body">

      <form method="post" action="{% url 'metcast:create' %}">
        {% csrf_token %}
        <label for="city">City:</label>
        <input type="text" id="city" name="city">
        <button type="submit">Отправить</button>
      </form>
      <script>
        $(function() {
            $("#city").autocomplete({
                source: "{% url 'metcast:city-autocomplete' %}",
                minLength: 2,
            });
        });
      </script>
    </div>
  </div>

</html>